### ISSUE TITLE
In a Repo created with GitWriter, manually added documents are not visible to the document lookup in the GitWriter splash screen.

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#11]
This issue follows from https://github.com/cwrc/CWRC-WriterBase/issues/10

After I was unable to save my test document into the newly created repository, I added it manually here: https://github.com/ilovan/CWRC-Writer-Tests/blob/master/test%20TEI%20letter

I tried to load it from the GitWriter splash page but the lookup could not locate it.

**Comment by jchartrand** [comment]
During the save process, the TEI document is ‘tagged’ as a CWRC Git document in the sense that we add an ‘ident' attribute with value CWRC-GitWriter-web-app

 to the ‘appInfo' element (which is something we talked about a while ago and confirmed with James Cummings).  Without that the GitHub api can’t filter specific repositories.

So, if you circumvent the normal save process, the ‘tag’ isn’t added, and your document won’t show up in the document list when you browse your CWRC enabled repositories.

To allow people to load non enabled CWRC repos, I could add an option to the dialog like ‘Show all of my repositories’ which would show every repository you have.  I’d also have to adjust the load mechanism to allow loading ‘non-cwrc’ repos.

**Comment by ilovan** [comment]
I think being able to access files that had been uploaded manually is a feature that could prove useful to users and something we would  eventually want to include, but it's not an absolute necessity at this point, provided https://github.com/cwrc/CWRC-WriterBase/issues/10 is fixed. 

I will assign this to @susanirenebrown for feedback and final decision.

**Comment by SusanBrown** [comment]
Being able to access saved or uploaded files is definitely key. Would like input from James on whether this is best done through the splash screen or some other way.

**Comment by jchartrand** [comment]
A good approach might be to provide a generic option to import a file via:

- file upload (i.e., from the user’s computer)
- a url (we’d retrieve the contents of a url that the user typed into a text input, and paste those contents into the CWRCWriter)
- paste (the user simply copy/pastes the document into the CWRC-Writer, which of course they can already do)

These would have nothing to do with GitHub (i.e., the GitWriter).  They’d be generic options available for any CWRC-Writer.

For people who happen to have XML files in GitHub repositories that aren’t ‘CWRC-enabled’ (a CWRC-enable repo has got a very specific structure and uses git versioning to produce tagged files for each annotation that can be dereferenced as linked data URIs) I’d suggest they just use one of the above options to import the document into the CWRC-Writer, and then if they want to save it back out to a new CWRC-enabled repo, they could do that.

Trying to CWRC-enable arbitrary existing TEI documents in arbitrary existing GitHub repositories would be difficult since CWRC-enabled repositories have a specific structure - there’d be all sorts of edge cases, and I just can’t imagine that it’s worth the effort anyhow since people could get the document into a CWR-enabled repository in other ways.

One nice feature would be to allow people to edit an arbitrary Github file (from an arbitrary repository that they own or have rights to) in the CWRC-Writer, and we save it back to the same repository for them.  We couldn’t easily, though, expand the annotations into separate files (which is how we wanted to give each annotation it’s own linked data URI) since we can’t control the structure of their existing repository.  The annotations could, though, be stored in the header (which is what we are doing now anyhow, and in fact looking at the code now, I see that we don’t even yet expand the annotations out into independent files for some reason that I can now only vaguely remember we talked about - I think it was something about wanting to keep everything in the header at the time.)  

This generic GitHub option would still require some amount of work (to build a new interface for browsing arbitrary repositories, tracking the location of the file so we can save it back to the same place later, and probably other things I can’t think of right now).

But, if you did no longer want annotations expand out into dereferenceable URIs, but were content to keep them in the header, then maybe moving away from the very specific ‘CWRC-enabled’ repos to instead support single files in any GitHub repo, might be the better option?

**Comment by susanirenebrown** [comment]
Thanks for outlining this, James.

I think that retaining the option of having the annotations be dereferencable is important given our use of the OA framework. So my thinking is that we should go with the generic option as outlined below, and then give them to option to save to a new CWRC-Writer-enabled repo.

I think we want to retain the option of keeping the files in the header for some projects, while others will want them expanded into separate annotations with URIs.

cheers,
Susan

**Comment by ilovan** [comment]
**Final decision:**

- allow Git-Writer to load a document from:
       - CWRC-enabled repositories 
       - URL
       - local machine upload

- Git-Writer should save docs uploaded through (2) and (3) above to CWRC-enabled repositories

- Do't allow Git-Writer to recognise xml documents manually uploaded to CWRC-enabled repositories.

**Comment by jchartrand** [comment]
Probably the most efficient way to proceed now is for you to sketch out how you’d like these uploads to work in the GUI.  Where they should be available, how the user is prompted, what text should be used with the dialog and it’s fields (if there is a dialog), etc.
