### ISSUE TITLE
Indicate what entities are newly converted upon ingestion.

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-WriterBase#154]
The message that appears when one is loading a document asking if one wants to create new entities could be improved in two ways.

1) through a link to documentation that would explain what is going on to the uninitiated. @ajmacdonald is it possible to provide a hyperlink to the documentation?

2) if there could be some indication of what entities would be converted so people would have some guidance about whether or not to say yes. How hard would it be to list the first few strings that would be converted?

Alternatively, and far better, could we pop them over into the NERVE interface, show them as candidate entities, and let people process them?

I think that as things stand, this would be quite anxiety-producing for some folks, and it is potentially a problem not to know which entities have just been created.

**Comment by ajmacdonald** [comment]
It's certainly possible to rework the dialog to show the text contents of the entities, but like you suggest, it probably makes sense to move this to the NERVE or Entities panels. Instead of performing this conversion on ingestion, a button could be added to the Entities panel that would trigger it. I suggest the Entities panel instead of the NERVE panel because while similar, it's a different process: identification based on tag vs. identification based on text content.

**Comment by ilovan** [comment]
I think we need to give some thought to how to integrate into the entity panel to have it somewhat match the NERVE panel interface. I'll throw a couple of sketches and plop them here.
