### ISSUE TITLE
Upgrade Islandora CWRC-Writer

### ISSUE THREAD

**Issue by jchartrand** [cwrc/CWRC-WriterBase#2]
Upgrade the Islandora version of the CWRC-Writer to use the latest CWRC-WriterBase.

**Comment by jefferya** [comment]
Notes that describe what the current integration does (i.e., what it overrides in the CWRC-Writer) and where it integration lives.

The current integration module uses the JS found at the following directory to override certain aspects of the CWRC-Writer - https://github.com/cwrc/islandora_cwrc_writer/tree/7.x/js

The above JS files are instantiated within a Drupal theme for the CWRC-Writer and passing in config settings from islandora_cwrc_document Schema objects and static config properties stored by the Drupal module -  https://github.com/cwrc/islandora_cwrc_writer/tree/7.x/theme

What is overridden by the islandora_cwrc_writer integration module?

This is not a complete list:

* The integration module stores the "schema" information contained within [writerConfig.js](https://github.com/cwrc/CWRC-Writer/blob/master/src/js/writerConfig.js) and passes the information to CWRC-Writer via the "Drupal.CWRCWriter.writer" object.

* custom mechanism to instantiate CWRC-Writer and onLoad handler

* overriding the CWRC-Writer file manager

* overriding the save and save/exit actions

* overriding the load actions to pass the "schemaId" to the load action so that a given "schema" can have multiple CSS (e.g., cwrc_tei_lite.rng can have different CSS files attached but use the same elements for entities such as names)

* how errors within CWRC-Writer are communicated

* create both a editing and read-only interface option 

* override the "Note" (i.e., mini CWRC-Writer for editing notes and researchnotes) handling via the load, init, setup, and passing in the schema handling into the CWRC-Writer codebase via the converter.processDocument.
