### ISSUE TITLE
Notes (research, scholarly) defaulting to <P> child, even when the schema does not allow it. 

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#31]
See Orlando biography docs.

**Comment by ilovan** [comment]
Hm, it's still doing it on http://dev-cwrc-writer.cwrc.ca/# (cache cleared)

**Comment by ajmacdonald** [comment]
@ilovan the updated code is not there yet.
I closed the issue because it's fixed in the repository. Please let me know what you'd like my approach to be regarding closing issues.

**Comment by jchartrand** [comment]
It is common to close an issue with a commit, so much so that commit messages allow one to insert ‘closes #23’ in the commit to have Github automatically close the issue when the commit is made.

Perhaps what we need is to make it our practice to redeploy to the dev server whenever a commit is made that should be tested?  And to also then move an issue from ‘on deck’ or ‘in progress’ (or whatever column we are using for work that is in progress), to ‘testable’ (or some such similarly named column), when the fix has been deployed to the dev server.
