### ISSUE TITLE
Update javascript libraries mentioned in the warning messages we received from GitHub

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-WriterBase#71]

**Comment by ajmacdonald** [comment]
This is one of them updated: https://github.com/cwrc/CWRC-WriterBase/commit/fc3aacb1a00662b0e362b000d423a103018cc36c

**Comment by jchartrand** [comment]
should all now be updated

**Comment by ilovan** [comment]
@ajmacdonald , @jchartrand 

I am reopening this because I have just received 10 additional  warnings re security vulnerabilities such as [this](https://github.com/cwrc/geonames-entity-lookup/network/dependencies).

Is there a way we could permanently fix this? (it seams to be a rather recent recurrent issue)

**Comment by jchartrand** [comment]
1.  I would open a new issue, because these newly reported vulnerabilities are different vulnerabilities than those we've already fixed (some of which I coincidentally fixed this morning).  It is better to have individual issues for separate problems, for posterity, and for project tracking.  We should never ‘reuse’ issues.  In fact, there should probably be one issue for each vulnerability in each CWRC repository.

2.  There is no way to permanently fix this.  Github is very nicely telling us, as it discovers vulnerabilities in public packages, that we are vulnerable because we use the packages.  You might even expect more of these warnings as time goes on, since it seems something new that Github is doing, and they might get better at detecting the vulnerabilities (I just in fact now checked, and Github says as much here:  https://blog.github.com/2017-11-16-introducing-security-alerts-on-github/.)  There may be a way to tell Github not to check these things, but that probably amounts to wilful blindness.
