### ISSUE TITLE
Structure panel contents disappearing during editing session

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-WriterBase#74]
This is going to be very hard to track down, I fear, and I can't tell if it's the base code or something to do with Islandora.

Two people of 6 editing files in the (older) embedded CWRC-Writer in this project meeting have had the entire contents of their structure panel disappear on them, and in one case a few but not all of the tagged entities also disappeared from the structure panel. 

In both cases we saved the doc, then I unlocked the object and opened it in and the structure panel reappeared.

The two files in question are:

http://beta.cwrc.ca/islandora/object/reed%3Abe530195-bb4e-4f28-91ba-a0e2d25dbb64/edit-cwrc#reed:be530195-bb4e-4f28-91ba-a0e2d25dbb64 (this is the one from which some entities disappeared as well)

http://beta.cwrc.ca/islandora/object/reed%3Af281652e-df7f-49b6-bf1a-9e1d198d64d1/edit-cwrc#reed:f281652e-df7f-49b6-bf1a-9e1d198d64d1

The time at which this happened was around 10:30 or 11 Eastern this morning. Neither document was valid.

@ilovan I don't think this is a known issue. Is that correct? Given that we are about to update the embedded CWRC-Writer I think it is probably best for the moment to 1) add to the documentation a note that if information disappears from the structure panel, users should save, exit, and reload the document; 2) see if we can replicate the error after we've updated.

**Comment by ilovan** [comment]
@SusanBrown , I tested the new integrated CWRC-Writer and the GitWriter in much more detail than the old CWRC-Writer and I haven't encountered this issue there. I'll add a troubleshooting section to the CWRC-Writer documentation

**Comment by ilovan** [comment]
@SusanBrown , update:

I talked to the RAs who've been testing both the old and the new Writer and they said that they encountered this issue as well, but only in the old version of the software. 

I will ad a troubleshooting section to the documentation, but I think the advise to save, exit and reload should be a more general one, not only for this specific problem.

Re this specific problem, since we don't have a profiling attribute for the old CWRC-Writer and we are not generating specific documentation for it, I would hesitate to put something so specific to it in the documentation, especially now when we are so close to replacing it altogether.

**Comment by SusanBrown** [comment]
Agree.
