### ISSUE TITLE
Annotation id generation

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-WriterBase#79]
In reviewing the changes to the file associated with the recent problem, I noticed that the annotation ids change quite dramatically from one version to the next. 

This is the file I was looking at:
https://github.com/megwils0n/Emoji-Spells-Which-Hopefully-Will-Work-With-Me/blob/master/document.xml

I've been looking at line 54 and for commit 13a6119 the annotation ID changes from 885 to 1180
For 477e3ba it changed from 1180 to 17
For 260f08c it changed from 17-313

@jchartrand or @ajmacdonald could you please exchange the reason for this?

**Comment by jchartrand** [comment]
That id, i.e., 

xpointer(//ref[@annotationId="ent_2088”])

Is the identifier for the XML element (in the document) to which the annotation points.  It is specific to the given version of the document (as far as I know) and so can change freely between versions (git commits in this case).  Is there another reason for wanting to keep it consistent (keeping in mind that this would probably be very hard to do)?

However, the identifier of the annotation itself, line 33:

<rdf:Description xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" rdf:about="undefined”>

Is ‘undefined’ which is, at least as far as the linked data part of his all goes, a problem.  There should at the very least be a value here, preferably a dereferencable URI, but at least a UUID.  This is probably the identifier you hoped would remain consistent across document versions, to suggest a relationship between the annotations in different versions of the document (ie., to record that they are the same annotation).  

We never did deal completely with versioning, though.  And, I suspect that we probably wouldn’t keep the same URI (or UUID) for the same annotation in different documents, because they are effectively different annotations — they point to different documents with different contexts.  Better would probably be to link the different versions of the annotations as some kind of chain with assertions like ‘versionOf’ ‘follows’’precedes’ (or whatever ontology is now appropriate for making such assertions - Memento was at one point I think a possibility - http://mementoweb.org/guide/quick-intro/ <http://mementoweb.org/guide/quick-intro/>)

We’ve talked a few times about how the annotation portion of the gitwriter saving isn’t yet complete (for example, to write in the URI/UUID that is now missing), and I’m pretty sure it is a GitHub issue.

Part of the reason we may have held back on fixing the gitwriter annotations is that we have also talked about how the RDF in the CWRC-Writer is now very old, and needs to be updated to a more recent version of OA (which may also be an existing issue.)

**Comment by ajmacdonald** [comment]
Every time an annotation is added, a unique ID is generated:
https://github.com/cwrc/CWRC-WriterBase/blob/master/src/js/tagger.js#L590
https://github.com/cwrc/CWRC-WriterBase/blob/master/src/js/writer.js#L132

We're relying on tinymce's ID generator, which increments the number each time it's called. So, the longer you use the writer, the higher the IDs will be.

It should be noted that loading a document will also set the tinymce ID number:
https://github.com/cwrc/CWRC-WriterBase/blob/master/src/js/converter.js#L825
So, making many edits to a document will over time create very large ID numbers.

**Comment by ajmacdonald** [comment]
The undefined values should've been populated through this "temporary" UUID generation code: https://github.com/cwrc/CWRC-WriterBase/blob/master/src/js/utilities.js#L1141-L1224
I'm not sure why that didn't happen.

**Comment by SusanBrown** [comment]
Needs more followup to figure out what's happening with UUID generation.

Bring together with work by Joel to update the annotation formats.
Consider in relation to matters of versioning; make annotations independent obects, etc.

**Comment by SusanBrown** [comment]
This is now moot, right @ajmacdonald ? Can close?

**Comment by ajmacdonald** [comment]
Correct @SusanBrown

**Comment by ajmacdonald** [comment]
Closing
